on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tools
        run: |
          python -m pip install pip pipenv
          pipenv sync

      - name: Pylint
        run: pipenv run pylint src

      - name: Flake8
        run: pipenv run flake8 .

      - name: Test
        run: pipenv run pytest

      - name: Package
        run: pipenv run python -m build

      - name: Security check
        run: pipenv check
        continue-on-error: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package-${{ matrix.python-version }}
          path: dist
